### ISSUE TITLE
readme.md was not added with other addons

### ISSUE THREAD

**Issue by slillo** [tuchk4/storybook-readme#102]
I'm using also [storysource addon](https://github.com/storybooks/storybook/tree/master/addons/storysource), if storysource addon panel is the first panel openend when I open storybook on browser and I try to switch to readme panel I get this error:
> README.md was not added.

It' not a problem related to webpack indeed, if I switch to readme panel and refresh page README.md is  shown as expected.

![storyreadme](https://user-images.githubusercontent.com/12492340/48213483-363aae80-e37e-11e8-925a-d20e624d400d.gif)

**Comment by Todmy** [comment]
same problem

**Comment by tuchk4** [comment]
Sorry for late response.
Going to investigate this issue tomorrow

**Comment by emmenko** [comment]
I had a quick look and the issue seems related to the `channel` event not being executed when switching to the "README" tab.

https://github.com/tuchk4/storybook-readme/blob/2f7877c6f297105a44aa80200cfd4df5fb921081/packages/storybook-readme/src/components/ReadmePanel.js#L23-L34

If however the page is loaded with the tab already being selected, the `channel` gets correctly called.

Maybe this helps further investigating the issue, I'm not familiar with the internals and how storybook addons work.

**Comment by tuchk4** [comment]
@emmenko Yeah. I already have fix and I going to find some time to prepare release with another fixes.
Going to to do this in nearest time

**Comment by tuchk4** [comment]
Duplicate #105

**Comment by tuchk4** [comment]
fixed at #105
