### ISSUE TITLE
Compile to ES2015

### ISSUE THREAD

**Issue by axelboc** [tuchk4/storybook-readme#41]
I'm using Jest for testing, which runs in a Node environment, and it fails on this add-on because the `import` statements are not compiled down to ES2015 (Node doesn't yet support ES6 modules):

```
[...]/node_modules/storybook-readme/with-readme.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                         ^^^^^^

SyntaxError: Unexpected token import
```

Jest has a transformer called `babel-jest` that can transform ES6 modules, but by default everything in `node_modules` is ignored for performance reasons. The workaround, which is far from idea, is to remove `node_modules` from the list of ignored transform patterns (in `package.json`):

```json
"jest": {
  "transform": {
    "^.+\\.js$": "<rootDir>/node_modules/babel-jest"
  },
  "transformIgnorePatterns": []
}
```

**Comment by tuchk4** [comment]
it is related to react-app (from create-react-app) babel preset.

https://github.com/facebookincubator/create-react-app/issues/3334


I would like to use react-app preset but I think I will make the same babel config as at storybook https://github.com/storybooks/storybook/blob/master/.babelrc

**Comment by TheRaven** [comment]
I had a similar problem but im using it with Vue components and storyshots.
Instead of removing node_modules completely from `transformIgnorePattern` I was able to make it work with something like this:

`"/node_modules/(?!(storybook-readme|rockey-react|@storybook/.*\\.vue$))"`

One thing I was not able to do, is use the `__docs` property. I had to add this config for jest:
`"^.+\\.md?$": "markdown-loader-jest"` to be able to use markdown files. The custom webpack.config.js from storybook is not used at all when running jest tests with storyshots

**Comment by bcbrian** [comment]
If you are running into this issue when using `Jest` for testing I suggests using mocking. I think it is the correct way to handle this because it is not your responsibility to test that this plugin works. Here is how I solved this. Some googling can help you find this info as well.
> Note: I import like this `import { withReadme } from 'storybook-readme';`
```
// ./src/__mocks__/storybook-readme.js

export const withReadme = (readmes, callback) => callback;
export default withReadme;
```
This allows the storybook render function to get passed back correctly. You might need to tweak based on you implementation.

**Comment by B3Kay** [comment]
> If you are running into this issue when using `Jest` for testing I suggests mocking. I think it is the correct way to handle this because it is not your responsibility to test that this plugin works. Here is how I solved this. Some googling can help you find this info as well.
> 
> > Note: I import like this `import { withReadme } from 'storybook-readme';`
> 
> ```
> // ./src/__mocks__/storybook-readme.js
> 
> export const withReadme = (readmes, callback) => callback;
> export default withReadme;
> ```
> This allows the storybook render function to get passed back correctly. You might need to tweak based on you implementation.

Could you create a more detailed description of how this is done?
