### ISSUE TITLE
Support with jest and storyshots

### ISSUE THREAD

**Issue by shanplourde** [tuchk4/storybook-readme#53]
Hello, I'm using .withDocs() to load some markdown for a story, which works fine. But when I try to run our jest tests, the test suite fails. Any ideas? Apologies if I'm missing something basic.

test console:

Test suite failed to run
README.md: Unexpected character '#' (1:0)

It's failing because the jest runner doesn't know how to interpret the README.md:

import readme from '../README.md';

Thanks

**Comment by tuchk4** [comment]
yes, you got error because jest does not know how to work with md files.
there are few options to resolve this:

* Configure `jest.tranform` as I wrote here https://github.com/tuchk4/storybook-readme/issues/52#issuecomment-366975185
* Use mocks https://github.com/tuchk4/storybook-readme/issues/41#issuecomment-364700001

**Comment by shanplourde** [comment]
Thanks Valerii, that was it
