### ISSUE TITLE
Override prism styles

### ISSUE THREAD

**Issue by joepuzzo** [tuchk4/storybook-readme#61]
Any suggestions on how i would override the prism stylesheets? it seems the second i import the withDocs HOC it will also pull in your styles which lay on top of mine. Basically i want to use a custom prism stylesheet in place of the one that gets bundled with this lib.

**Comment by tuchk4** [comment]
styles are inserted as last element inside`<head/>` when app is loaded.

https://github.com/tuchk4/storybook-readme/blob/master/packages/storybook-readme/src/styles/prism-theme-css.js#L153

Maybe that using `prepend` styles instead of `append` should help to resolve this issue.

What do you think @joepuzzo ? Feel free to submit PR :)

**Comment by andrei-ilyukovich** [comment]
@joepuzzo you could create `manager-head.html` with global styles which override some prism styles
[Add Custom Head Tags](https://storybook.js.org/configurations/add-custom-head-tags/#add-tags-or-scripts-to-the-main-ui)
```html
<style type="text/css">
    .Pane.horizontal.Pane2 .markdown-body {
        color: #ffffff;
    }

    .Pane.horizontal.Pane2 .markdown-body table tr {
        background-color: #373737;
    }

    .Pane.horizontal.Pane2  .markdown-body table tr:nth-child(2n) {
        background-color: #242424;
    }
</style>
```
